spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: tianhao
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        max-active: 20
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        validation-query: select 'x'
        time-between-eviction-runs-millis: 60000
        test-while-idle: true
        min-evictable-idle-time-millis: 300000
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
    messages:
        encoding: utf-8
    session:
        store-type: hash_map
    http:
      multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 20MB
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          ddl-auto: create
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        call-setters-on-nulls: true
        default-json-type-handler: com.tianhaox.mybatis.type.FastJsonTypeHandler

logging:
  level: debug

